#!/usr/bin/env bash
# ScreenReader launcher — auto-generated by setup.sh
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/.venv/bin/activate"
exec python3 "$SCRIPT_DIR/screenreader.py" "$@"
