#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# ScreenReader — Setup Script for Debian Trixie
# Installs: Tesseract, espeak-ng, Piper TTS + en_US voice, Python deps
# Then creates a .desktop launcher for one-click use
# Run once: bash setup.sh
# ─────────────────────────────────────────────────────────────────────────────

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VENV_DIR="$SCRIPT_DIR/.venv"
PIPER_DIR="$HOME/.local/share/piper"
VOICES_DIR="$HOME/.local/share/piper-voices"
BIN_DIR="$HOME/.local/bin"

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
info()  { echo -e "${GREEN}[INFO]${NC}  $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC}  $*"; }
error() { echo -e "${RED}[ERROR]${NC} $*"; }

echo ""
echo "╔══════════════════════════════════════════════╗"
echo "║     ScreenReader — Setup for Debian Trixie  ║"
echo "╚══════════════════════════════════════════════╝"
echo ""

# ─── 1. System packages ───────────────────────────────────────────────────────
info "Installing system packages..."
sudo apt-get update -qq
sudo apt-get install -y -qq \
    python3 python3-pip python3-venv python3-tk \
    tesseract-ocr tesseract-ocr-eng \
    espeak-ng \
    libnotify-bin \
    alsa-utils \
    wget curl xdg-utils \
    2>/dev/null || true

info "System packages done."

# ─── 2. Python virtual environment ───────────────────────────────────────────
info "Creating Python virtual environment at $VENV_DIR ..."
python3 -m venv "$VENV_DIR"
source "$VENV_DIR/bin/activate"

pip install --upgrade pip -q
pip install -q \
    Pillow \
    pytesseract \
    pynput

info "Python packages installed."

# ─── 3. Piper TTS binary ─────────────────────────────────────────────────────
PIPER_INSTALLED=false

if command -v piper &>/dev/null; then
    info "Piper TTS already installed at $(which piper)"
    PIPER_INSTALLED=true
else
    info "Downloading Piper TTS binary..."
    mkdir -p "$PIPER_DIR" "$BIN_DIR"

    # Detect architecture
    ARCH=$(uname -m)
    case "$ARCH" in
        x86_64)  PIPER_ARCHIVE="piper_linux_x86_64.tar.gz" ;;
        aarch64) PIPER_ARCHIVE="piper_linux_aarch64.tar.gz" ;;
        armv7l)  PIPER_ARCHIVE="piper_linux_armv7l.tar.gz" ;;
        *)
            warn "Unknown architecture $ARCH — skipping Piper. Will use espeak-ng."
            PIPER_INSTALLED=false
            ;;
    esac

    if [[ -n "${PIPER_ARCHIVE:-}" ]]; then
        PIPER_URL="https://github.com/rhasspy/piper/releases/latest/download/$PIPER_ARCHIVE"
        info "Fetching: $PIPER_URL"
        if wget -q --show-progress -O "$PIPER_DIR/$PIPER_ARCHIVE" "$PIPER_URL"; then
            tar -xzf "$PIPER_DIR/$PIPER_ARCHIVE" -C "$PIPER_DIR" --strip-components=1
            rm -f "$PIPER_DIR/$PIPER_ARCHIVE"
            chmod +x "$PIPER_DIR/piper"
            ln -sf "$PIPER_DIR/piper" "$BIN_DIR/piper"
            info "Piper installed → $PIPER_DIR/piper"
            PIPER_INSTALLED=true
        else
            warn "Piper download failed. Will use espeak-ng as fallback."
        fi
    fi
fi

# ─── 4. Piper voice model ─────────────────────────────────────────────────────
VOICE_ONNX=""
if $PIPER_INSTALLED; then
    # Check if a voice already exists
    if find "$VOICES_DIR" -name "*.onnx" 2>/dev/null | grep -q .; then
        VOICE_ONNX=$(find "$VOICES_DIR" -name "*.onnx" | head -1)
        info "Piper voice already present: $VOICE_ONNX"
    else
        info "Downloading Piper English voice (en_US-amy-medium)..."
        mkdir -p "$VOICES_DIR/en_US/amy"

        BASE_URL="https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0/en/en_US/amy/medium"
        VOICE_ONNX="$VOICES_DIR/en_US/amy/en_US-amy-medium.onnx"
        VOICE_JSON="$VOICES_DIR/en_US/amy/en_US-amy-medium.onnx.json"

        if wget -q --show-progress -O "$VOICE_ONNX" "$BASE_URL/en_US-amy-medium.onnx" && \
           wget -q --show-progress -O "$VOICE_JSON" "$BASE_URL/en_US-amy-medium.onnx.json"; then
            info "Voice model downloaded: $VOICE_ONNX"
        else
            warn "Voice download failed. Will fall back to espeak-ng."
            rm -f "$VOICE_ONNX" "$VOICE_JSON"
            VOICE_ONNX=""
        fi
    fi
fi

# ─── 5. Launcher script ───────────────────────────────────────────────────────
LAUNCHER="$SCRIPT_DIR/run.sh"
cat > "$LAUNCHER" << LAUNCH
#!/usr/bin/env bash
# ScreenReader launcher — auto-generated by setup.sh
SCRIPT_DIR="\$(cd "\$(dirname "\${BASH_SOURCE[0]}")" && pwd)"
source "\$SCRIPT_DIR/.venv/bin/activate"
exec python3 "\$SCRIPT_DIR/screenreader.py" "\$@"
LAUNCH
chmod +x "$LAUNCHER"
info "Launcher created: $LAUNCHER"

# ─── 6. .desktop entry (system tray / app menu) ──────────────────────────────
DESKTOP_DIR="$HOME/.local/share/applications"
mkdir -p "$DESKTOP_DIR"

ICON_PATH="$SCRIPT_DIR/icon.png"

cat > "$DESKTOP_DIR/screenreader.desktop" << DESK
[Desktop Entry]
Version=1.0
Type=Application
Name=ScreenReader
Comment=Crop screen region → OCR → Speech (Ctrl+Shift+S)
Exec=$LAUNCHER
Icon=$ICON_PATH
Terminal=false
StartupNotify=true
Categories=Utility;Accessibility;
Keywords=ocr;tts;screen;read;accessibility;
DESK

chmod +x "$DESKTOP_DIR/screenreader.desktop"
xdg-desktop-menu forceupdate 2>/dev/null || true
info ".desktop entry installed → $DESKTOP_DIR/screenreader.desktop"

# ─── 7. Autostart (optional) ─────────────────────────────────────────────────
AUTOSTART_DIR="$HOME/.config/autostart"
mkdir -p "$AUTOSTART_DIR"
cat > "$AUTOSTART_DIR/screenreader.desktop" << AUTO
[Desktop Entry]
Type=Application
Name=ScreenReader
Exec=$LAUNCHER
Hidden=false
NoDisplay=false
X-GNOME-Autostart-enabled=true
AUTO
info "Autostart entry created — ScreenReader starts on login."

# ─── 8. Summary ───────────────────────────────────────────────────────────────
echo ""
echo "╔══════════════════════════════════════════════╗"
echo "║              Setup Complete!                 ║"
echo "╚══════════════════════════════════════════════╝"
echo ""
if $PIPER_INSTALLED && [[ -n "$VOICE_ONNX" ]]; then
    echo -e "  ${GREEN}✓${NC} Piper TTS  : $(which piper 2>/dev/null || echo $PIPER_DIR/piper)"
    echo -e "  ${GREEN}✓${NC} Voice      : $(basename $VOICE_ONNX)"
else
    echo -e "  ${YELLOW}⚠${NC} Piper not available — using espeak-ng (robotic but works)"
fi
echo -e "  ${GREEN}✓${NC} OCR        : $(tesseract --version 2>&1 | head -1)"
echo -e "  ${GREEN}✓${NC} Launcher   : $LAUNCHER"
echo ""
echo "  ▶  Launch now          :  bash $LAUNCHER"
echo "  ▶  Or open from menu   :  Search 'ScreenReader' in app launcher"
echo "  ▶  Hotkey (once open)  :  Ctrl + Shift + S"
echo ""
